version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: document_container
    restart: always
    env_file:
      - .env
    volumes:
      - document_mongo_data:/data/db
    ports:
      - '27017:27017'
    healthcheck:
      test: ['CMD', 'mongosh', '--eval', "db.runCommand('ping').ok"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: .
      target: dev # Chạy stage "dev"
    container_name: backend-app
    ports:
      - '3000:3000'
    env_file:
      - .env
    depends_on:
      mongo:
        condition: service_healthy
    restart: unless-stopped

volumes:
  document_mongo_data:
