version: '3.8'
services:
  mongo:
    image: mongo:latest
    container_name: document_container
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: Admin123
    volumes:
      - document_mongo_data:/data/db  
    ports:
      - "27017:27017"

volumes:
  document_mongo_data:
    name: document_mongo_data  
    driver: local